### ISSUE TITLE
Replace dummy content under "Business Goals" on Services page

### ISSUE THREAD

**Issue by UmerManager** [TaoFruit/reveltek#28]
Website link: https://reveltek.com/services.html#

**Follow these Instructions:**

- Change the dummy content and **headline** also under Business Goals
- Always consider character count and capitalization standards.
- Content should be relevant to Reveltek "Mission and Vision".
- You can get help from Reveltek Handbook.

Please find the attached image for reference:

![image](https://user-images.githubusercontent.com/111144473/206700500-2885a550-741c-4f1f-8809-5894b99e8249.png)

**Comment by Zaryabayub** [comment]
I would like this issue be assigned to me.
