### ISSUE TITLE
Do market research for "Our Core Features" on index page.

### ISSUE THREAD

**Issue by UmerManager** [TaoFruit/reveltek#33]
Website Link: https://reveltek.com/index.html

**Instructions to follow:**

* Do competitive market research for this section how other top tech consulting organization's websites look like.
* Do research for what are the services we provide as a tech consulting company
* You can visit our Reveltek Handbook for content reference also.

     * Handbookhttps://focushive.sharepoint.com/sites/Everyone/Shared%20Documents/General/Reveltek-Handbook%20(2).pdf

-
  Please find the attached image for reference:
![image](https://user-images.githubusercontent.com/111144473/207322939-523423fe-aecf-46be-ac9e-6a2e8ad13092.png)

**Comment by Zaryabayub** [comment]
The heading "Curiosity community" exceeds the max word count for any replacement.

**Comment by UmerManager** [comment]
@Zaryabayub I have updated this issue. You can work according to new instructions mentioned above.

**Comment by Zaryabayub** [comment]
@UmerManager It's already been merged by Mr. Hackney.
